[2022-02-15T16:04:17.377140] Entering context manager injector.
[2022-02-15T16:04:19.332917] context_manager_injector.py Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['diabetes_experiment.py'])
Script type = None
[2022-02-15T16:04:19.347922] Entering Run History Context Manager.
C:\Users\ag4488\.azureml\envs\azureml_2a26795ceaa057dc05a99cff9a3f7e3a\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
[2022-02-15T16:04:22.757925] Current directory: C:\Users\ag4488\AppData\Local\Temp\azureml_runs\mslearn-diabetes_1644941052_fd825f91
[2022-02-15T16:04:22.758925] Preparing to call script [diabetes_experiment.py] with arguments:[]
[2022-02-15T16:04:22.758925] After variable expansion, calling script [diabetes_experiment.py] with arguments:[]



[2022-02-15T16:04:22.812928] The experiment failed. Finalizing run...
[2022-02-15T16:04:22.812928] Start FinalizingInRunHistory
[2022-02-15T16:04:22.816927] Logging experiment finalizing status in history service.
Starting the daemon thread to refresh tokens in background for process with pid = 26416
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.30036330223083496 seconds
Traceback (most recent call last):
  File "diabetes_experiment.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\ag4488\.azureml\envs\azureml_2a26795ceaa057dc05a99cff9a3f7e3a\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\ag4488\.azureml\envs\azureml_2a26795ceaa057dc05a99cff9a3f7e3a\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


[2022-02-15T16:04:25.119297] Finished context manager injector with Exception.
